import streamlit as st
import requests
import json

# Backend API URL (Flask server)
BACKEND_URL = "http://localhost:5000/generate_project"

# Example Scientific Calculator Code (Key-Value Pairs)
DEFAULT_CODE = {
    "main.py": """
from calculator import ScientificCalculator

def main():
    print("Scientific Calculator")
    calc = ScientificCalculator()
    print("5 + 3 =", calc.add(5, 3))
    print("sin(30°) =", calc.sin(30))

if __name__ == "__main__":
    main()
""",
    "calculator/__init__.py": "",
    "calculator/calculator.py": """
import math
class ScientificCalculator:
    def add(self, a, b): return a + b
    def sin(self, degrees): return math.sin(math.radians(degrees))
""",
    "requirements.txt": "numpy\nsympy",
    "README.md": "# Scientific Calculator\n\nA Python project generated by Impact Vibe Coder."
}

st.title("Impact Vibe Coder - Project Generator")
st.write("Upload key-value code snippets or use the default example:")

# Text area for code input (JSON format)
# After getting the pranav key value pair we will edit this
user_code = st.text_area("Paste your code (key-value pairs):", value=json.dumps(DEFAULT_CODE, indent=2))

if st.button("Generate Project"):
    try:
        code_dict = json.loads(user_code)
        response = requests.post(BACKEND_URL, json=code_dict)
        if response.status_code == 200:
            st.success("Project generated successfully!")
            st.download_button(
                label="Download Project ZIP",
                data=response.content,
                file_name="scientific_calculator_project.zip",
                mime="application/zip"
            )
        else:
            st.error(f"Backend error: {response.text}")
    except Exception as e:
        st.error(f"Invalid input: {str(e)}")